---
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: 'buildApi'
    args:
      - "build"
      - "--target"
      - "api"
      - "."
      - "-t"
      - "eu.gcr.io/$PROJECT_ID/api:$TAG_NAME"
  - name: "gcr.io/cloud-builders/docker"
    id: 'buildFrontend'
    args:
      - "build"
      - "--target"
      - "frontend"
      - "."
      - "-t"
      - "eu.gcr.io/$PROJECT_ID/frontend:$TAG_NAME"
  - name: "gcr.io/cloud-builders/docker"
    id: 'pushApi'
    args:
      - "push"
      - "eu.gcr.io/$PROJECT_ID/api:$TAG_NAME"
    waitFor: ['buildApi']
  - name: "gcr.io/cloud-builders/docker"
    id: 'pushFrontend'
    args:
      - "push"
      - "eu.gcr.io/$PROJECT_ID/frontend:$TAG_NAME"
    waitFor: ['buildFrontend']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deployApi'
    args:
    - '-n'
    - 'api'
    - 'set'
    - 'image'
    - 'statefulsets'
    - 'api=eu.gcr.io/$PROJECT_ID/api:$TAG_NAME'
    - '--all'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=test'
    - 'CLOUDSDK_CORE_PROJECT=cluster-builder-test'
    waitFor: ['pushApi']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deployFrontend'
    args:
    - '-n'
    - 'frontend'
    - 'set'
    - 'image'
    - 'statefulsets'
    - 'frontend=eu.gcr.io/$PROJECT_ID/frontend:$TAG_NAME'
    - '--all'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=test'
    - 'CLOUDSDK_CORE_PROJECT=cluster-builder-test'
    waitFor: ['pushFrontend']