version: '3.5'
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    image: mongo
    volumes:
      - /Users/szabom/mongo/db:/data/db
  api:
    container_name: api
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    image: api:latest
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
  UI:
    container_name: ui
    build:
        context: .
        target: frontend
        dockerfile: Dockerfile
    image: ui:latest
    ports:
      - 8080:8080
    depends_on:
      - api
