version: '3.5'
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    image: mongo
    volumes:
      - /Users/szabom/mongo/db:/data/db
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo